<?php if ($this->pageCount > 1): ?>
    <div>
        <ul class="pagination">
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->route, [],
                        ['query' => ['page' => $this->previous]]) ?><?php if ($this->tag): ?>&tag=<?= $this->tag ?><?php endif; ?>">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            <?php endif ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page !== $this->current): ?>
                    <li class="page-item">
                        <a class="page-link"
                           href="<?= $this->url($this->route, [],
                               ['query' => ['page' => $page]]) ?><?php if ($this->tag): ?>&tag=<?= $this->tag ?><?php endif; ?>">
                            <?= $page ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item active">
                        <a class="page-link" href="#"><?= $page ?></a>
                    </li>
                <?php endif ?>
            <?php endforeach ?>
            <?php if (isset($this->next)): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->route, [],
                        ['query' => ['page' => $this->next]]) ?><?php if ($this->tag): ?>&tag=<?= $this->tag ?><?php endif; ?>">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            <?php endif ?>
        </ul>
    </div>
<?php endif ?>