<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="page-header col-12">
    <h1>Welcome to the Symfony Demo application</h1>
</div>
<div class="col-16">
    <div class="jumbotron">
        <p>
            Browse the public section of the demo application.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" href="<?= $this->url('blog') ?>">
                <i class="fa fa-users" aria-hidden="true"></i>Browse application
            </a>
        </p>
    </div>
</div>

<div class="col-6">
    <div class="jumbotron">
        <p>
            Browse the admin backend of the demo application.
        </p>
        <p>
            <a class="btn btn-primary btn-lg" href="<?= $this->url('home') ?>">
                <i class="fa fa-lock" aria-hidden="true"></i>Browse backend
            </a>
        </p>
    </div>
</div>