<div class="col-8 main">
    <div class="highlight">
        <form action="<?= $this->url('login') ?>" method="post">
            <fieldset>
                <legend><i class="fa fa-lock" aria-hidden="true"></i> Secure Sign in</legend>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" value="" class="form-control">
                    <?= $this->formElementErrors()->render($this->form->get('username'), ['class' => 'text-danger']) ?>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control">
                    <?= $this->formElementErrors()->render($this->form->get('password'), ['class' => 'text-danger']) ?>
                </div>
                <div class="form-group">
                    <?= $this->formElement($this->form->get('__csrf')) ?>
                </div>
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-sign-in" aria-hidden="true"></i> Sign in
                </button>
            </fieldset>
        </form>
    </div>
</div>